/**
 * Concrete-class aliases for ``macros/defaults.js``.
 *
 * Python's ``macros/defaults.py`` imports every default implementation at
 * module load. In ESM those imports would form evaluation cycles with the
 * packages that *use* the defaults, so the aliases are collected here, at the
 * bottom of the dependency graph, and re-exported by ``defaults.js``.
 *
 * The complete table is in the module docstring of ``defaults.js``.
 */
import { MultiBuffer } from "../data/multibuffer/multibuffer.js";
import { _LAILA_IDENTIFIABLE_POOL } from "../data/schema/base.js";
import { PythonAsyncThreadPoolTaskForce } from "../policy/central/command/taskforce/async_thread_pool_executor/taskforce.js";
import { _LAILA_IDENTIFIABLE_CENTRAL_COMMAND } from "../policy/central/command/schema/base.js";
import { _LAILA_IDENTIFIABLE_CELLULAR_COMM_PROTOCOL } from "../policy/central/communication/protocols/cellular/cellular.js";
import { _LAILA_IDENTIFIABLE_GSM_COMM_PROTOCOL } from "../policy/central/communication/protocols/cellular/gsm_gprs.js";
import { _LAILA_IDENTIFIABLE_LTE_COMM_PROTOCOL } from "../policy/central/communication/protocols/cellular/lte.js";
import { _LAILA_IDENTIFIABLE_NR5G_COMM_PROTOCOL } from "../policy/central/communication/protocols/cellular/nr5g.js";
import { _LAILA_IDENTIFIABLE_AMQP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/amqp.js";
import { _LAILA_IDENTIFIABLE_COAP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/coap.js";
import { _LAILA_IDENTIFIABLE_DDS_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/dds.js";
import { _LAILA_IDENTIFIABLE_DTLS_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/dtls.js";
import { _LAILA_IDENTIFIABLE_ETHERNET_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/ethernet.js";
import { _LAILA_IDENTIFIABLE_GRPC_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/grpc.js";
import { _LAILA_IDENTIFIABLE_HTTP2_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/http2.js";
import { _LAILA_IDENTIFIABLE_HTTP3_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/http3.js";
import { _LAILA_IDENTIFIABLE_MODBUS_TCP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/modbus_tcp.js";
import { _LAILA_IDENTIFIABLE_MQTT_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/mqtt.js";
import { _LAILA_IDENTIFIABLE_OPCUA_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/opcua.js";
import { _LAILA_IDENTIFIABLE_TCP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/tcp.js";
import { _LAILA_IDENTIFIABLE_TLS_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/tls.js";
import { _LAILA_IDENTIFIABLE_UDP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/udp.js";
import { _LAILA_IDENTIFIABLE_XMPP_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/xmpp.js";
import { _LAILA_IDENTIFIABLE_ZEROMQ_COMM_PROTOCOL } from "../policy/central/communication/protocols/ip_app/zeromq.js";
import { _LAILA_IDENTIFIABLE_LOOPBACK_COMM_PROTOCOL } from "../policy/central/communication/protocols/local/loopback.js";
import { _LAILA_IDENTIFIABLE_UNIXSOCKET_COMM_PROTOCOL } from "../policy/central/communication/protocols/local/unixsocket.js";
import { _LAILA_IDENTIFIABLE_LORA_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/lora.js";
import { _LAILA_IDENTIFIABLE_LORAWAN_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/lorawan.js";
import { _LAILA_IDENTIFIABLE_LTEM_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/ltem.js";
import { _LAILA_IDENTIFIABLE_NBIOT_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/nbiot.js";
import { _LAILA_IDENTIFIABLE_SATELLITE_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/satellite.js";
import { _LAILA_IDENTIFIABLE_SIGFOX_COMM_PROTOCOL } from "../policy/central/communication/protocols/lpwan/sigfox.js";
import { _LAILA_IDENTIFIABLE_ANT_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/ant.js";
import { _LAILA_IDENTIFIABLE_BLUETOOTH_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/bluetooth.js";
import { _LAILA_IDENTIFIABLE_ESPNOW_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/espnow.js";
import { _LAILA_IDENTIFIABLE_IRDA_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/irda.js";
import { _LAILA_IDENTIFIABLE_MATTER_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/matter.js";
import { _LAILA_IDENTIFIABLE_NFC_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/nfc.js";
import { _LAILA_IDENTIFIABLE_RFID_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/rfid.js";
import { _LAILA_IDENTIFIABLE_SIXLOWPAN_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/sixlowpan.js";
import { _LAILA_IDENTIFIABLE_THREAD_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/thread.js";
import { _LAILA_IDENTIFIABLE_UWB_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/uwb.js";
import { _LAILA_IDENTIFIABLE_WIFI_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/wifi.js";
import { _LAILA_IDENTIFIABLE_WIFIDIRECT_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/wifi_direct.js";
import { _LAILA_IDENTIFIABLE_ZIGBEE_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/zigbee.js";
import { _LAILA_IDENTIFIABLE_ZWAVE_COMM_PROTOCOL } from "../policy/central/communication/protocols/short_range/zwave.js";
import { _LAILA_IDENTIFIABLE_TCPIP_COMM_PROTOCOL } from "../policy/central/communication/protocols/tcpip.js";
import { _LAILA_IDENTIFIABLE_CAN_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/can.js";
import { _LAILA_IDENTIFIABLE_ENIP_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/enip.js";
import { _LAILA_IDENTIFIABLE_ETHERCAT_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/ethercat.js";
import { _LAILA_IDENTIFIABLE_I2C_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/i2c.js";
import { _LAILA_IDENTIFIABLE_I2S_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/i2s.js";
import { _LAILA_IDENTIFIABLE_LIN_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/lin.js";
import { _LAILA_IDENTIFIABLE_MODBUS_RTU_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/modbus_rtu.js";
import { _LAILA_IDENTIFIABLE_ONEWIRE_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/one_wire.js";
import { _LAILA_IDENTIFIABLE_PROFINET_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/profinet.js";
import { _LAILA_IDENTIFIABLE_RS232_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/rs232.js";
import { _LAILA_IDENTIFIABLE_RS485_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/rs485.js";
import { _LAILA_IDENTIFIABLE_SDIO_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/sdio.js";
import { _LAILA_IDENTIFIABLE_SPI_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/spi.js";
import { _LAILA_IDENTIFIABLE_UART_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/uart.js";
import { _LAILA_IDENTIFIABLE_USB_COMM_PROTOCOL } from "../policy/central/communication/protocols/wired/usb.js";
import { _LAILA_IDENTIFIABLE_COMMUNICATION } from "../policy/central/communication/schema/base.js";
import { _LAILA_IDENTIFIABLE_POOL_ROUTER } from "../policy/central/memory/router/pool_router.js";
import { _LAILA_IDENTIFIABLE_CENTRAL_MEMORY } from "../policy/central/memory/schema/base.js";
import { _LAILA_IDENTIFIABLE_POLICY } from "../policy/schema/base.js";

export const DefaultTaskForce = PythonAsyncThreadPoolTaskForce;
export const DefaultCentralCommand = _LAILA_IDENTIFIABLE_CENTRAL_COMMAND;
export const DefaultCentralCommunication = _LAILA_IDENTIFIABLE_COMMUNICATION;
export const DefaultTCPIPProtocol = _LAILA_IDENTIFIABLE_TCPIP_COMM_PROTOCOL;
export const DefaultWebSocketProtocol = _LAILA_IDENTIFIABLE_TCPIP_COMM_PROTOCOL;
export const DefaultTCPProtocol = _LAILA_IDENTIFIABLE_TCP_COMM_PROTOCOL;
export const DefaultUDPProtocol = _LAILA_IDENTIFIABLE_UDP_COMM_PROTOCOL;
export const DefaultTLSProtocol = _LAILA_IDENTIFIABLE_TLS_COMM_PROTOCOL;
export const DefaultEthernetProtocol = _LAILA_IDENTIFIABLE_ETHERNET_COMM_PROTOCOL;
export const DefaultWiFiProtocol = _LAILA_IDENTIFIABLE_WIFI_COMM_PROTOCOL;
export const DefaultWiFiDirectProtocol = _LAILA_IDENTIFIABLE_WIFIDIRECT_COMM_PROTOCOL;
export const DefaultCellularProtocol = _LAILA_IDENTIFIABLE_CELLULAR_COMM_PROTOCOL;
export const DefaultGSMProtocol = _LAILA_IDENTIFIABLE_GSM_COMM_PROTOCOL;
export const DefaultLTEProtocol = _LAILA_IDENTIFIABLE_LTE_COMM_PROTOCOL;
export const DefaultNR5GProtocol = _LAILA_IDENTIFIABLE_NR5G_COMM_PROTOCOL;
export const DefaultNBIoTProtocol = _LAILA_IDENTIFIABLE_NBIOT_COMM_PROTOCOL;
export const DefaultLTEMProtocol = _LAILA_IDENTIFIABLE_LTEM_COMM_PROTOCOL;
export const DefaultMatterProtocol = _LAILA_IDENTIFIABLE_MATTER_COMM_PROTOCOL;
export const DefaultSigfoxProtocol = _LAILA_IDENTIFIABLE_SIGFOX_COMM_PROTOCOL;
export const DefaultSatelliteProtocol = _LAILA_IDENTIFIABLE_SATELLITE_COMM_PROTOCOL;
export const DefaultUSBProtocol = _LAILA_IDENTIFIABLE_USB_COMM_PROTOCOL;
export const DefaultLoRaWANProtocol = _LAILA_IDENTIFIABLE_LORAWAN_COMM_PROTOCOL;
export const DefaultSixLoWPANProtocol = _LAILA_IDENTIFIABLE_SIXLOWPAN_COMM_PROTOCOL;
export const DefaultZigbeeProtocol = _LAILA_IDENTIFIABLE_ZIGBEE_COMM_PROTOCOL;
export const DefaultThreadProtocol = _LAILA_IDENTIFIABLE_THREAD_COMM_PROTOCOL;
export const DefaultZWaveProtocol = _LAILA_IDENTIFIABLE_ZWAVE_COMM_PROTOCOL;
export const DefaultNFCProtocol = _LAILA_IDENTIFIABLE_NFC_COMM_PROTOCOL;
export const DefaultRFIDProtocol = _LAILA_IDENTIFIABLE_RFID_COMM_PROTOCOL;
export const DefaultUWBProtocol = _LAILA_IDENTIFIABLE_UWB_COMM_PROTOCOL;
export const DefaultIrDAProtocol = _LAILA_IDENTIFIABLE_IRDA_COMM_PROTOCOL;
export const DefaultANTProtocol = _LAILA_IDENTIFIABLE_ANT_COMM_PROTOCOL;
export const DefaultESPNowProtocol = _LAILA_IDENTIFIABLE_ESPNOW_COMM_PROTOCOL;
export const DefaultUnixSocketProtocol = _LAILA_IDENTIFIABLE_UNIXSOCKET_COMM_PROTOCOL;
export const DefaultLoopbackProtocol = _LAILA_IDENTIFIABLE_LOOPBACK_COMM_PROTOCOL;
export const DefaultMQTTProtocol = _LAILA_IDENTIFIABLE_MQTT_COMM_PROTOCOL;
export const DefaultAMQPProtocol = _LAILA_IDENTIFIABLE_AMQP_COMM_PROTOCOL;
export const DefaultZeroMQProtocol = _LAILA_IDENTIFIABLE_ZEROMQ_COMM_PROTOCOL;
export const DefaultUARTProtocol = _LAILA_IDENTIFIABLE_UART_COMM_PROTOCOL;
export const DefaultRS232Protocol = _LAILA_IDENTIFIABLE_RS232_COMM_PROTOCOL;
export const DefaultRS485Protocol = _LAILA_IDENTIFIABLE_RS485_COMM_PROTOCOL;
export const DefaultCANProtocol = _LAILA_IDENTIFIABLE_CAN_COMM_PROTOCOL;
export const DefaultModbusTCPProtocol = _LAILA_IDENTIFIABLE_MODBUS_TCP_COMM_PROTOCOL;
export const DefaultModbusRTUProtocol = _LAILA_IDENTIFIABLE_MODBUS_RTU_COMM_PROTOCOL;
export const DefaultI2CProtocol = _LAILA_IDENTIFIABLE_I2C_COMM_PROTOCOL;
export const DefaultSPIProtocol = _LAILA_IDENTIFIABLE_SPI_COMM_PROTOCOL;
export const DefaultENIPProtocol = _LAILA_IDENTIFIABLE_ENIP_COMM_PROTOCOL;
export const DefaultLINProtocol = _LAILA_IDENTIFIABLE_LIN_COMM_PROTOCOL;
export const DefaultOneWireProtocol = _LAILA_IDENTIFIABLE_ONEWIRE_COMM_PROTOCOL;
export const DefaultI2SProtocol = _LAILA_IDENTIFIABLE_I2S_COMM_PROTOCOL;
export const DefaultSDIOProtocol = _LAILA_IDENTIFIABLE_SDIO_COMM_PROTOCOL;
export const DefaultProfinetProtocol = _LAILA_IDENTIFIABLE_PROFINET_COMM_PROTOCOL;
export const DefaultEtherCATProtocol = _LAILA_IDENTIFIABLE_ETHERCAT_COMM_PROTOCOL;
export const DefaultCoAPProtocol = _LAILA_IDENTIFIABLE_COAP_COMM_PROTOCOL;
export const DefaultHTTP2Protocol = _LAILA_IDENTIFIABLE_HTTP2_COMM_PROTOCOL;
export const DefaultHTTP3Protocol = _LAILA_IDENTIFIABLE_HTTP3_COMM_PROTOCOL;
export const DefaultDTLSProtocol = _LAILA_IDENTIFIABLE_DTLS_COMM_PROTOCOL;
export const DefaultXMPPProtocol = _LAILA_IDENTIFIABLE_XMPP_COMM_PROTOCOL;
export const DefaultDDSProtocol = _LAILA_IDENTIFIABLE_DDS_COMM_PROTOCOL;
export const DefaultOPCUAProtocol = _LAILA_IDENTIFIABLE_OPCUA_COMM_PROTOCOL;
export const DefaultGRPCProtocol = _LAILA_IDENTIFIABLE_GRPC_COMM_PROTOCOL;
export const DefaultLoRaProtocol = _LAILA_IDENTIFIABLE_LORA_COMM_PROTOCOL;
export const DefaultBluetoothProtocol = _LAILA_IDENTIFIABLE_BLUETOOTH_COMM_PROTOCOL;
export const DefaultCentralMemory = _LAILA_IDENTIFIABLE_CENTRAL_MEMORY;
export const DefaultPolicy = _LAILA_IDENTIFIABLE_POLICY;
export const DefaultPool = _LAILA_IDENTIFIABLE_POOL;
export const DefaultPoolRouter = _LAILA_IDENTIFIABLE_POOL_ROUTER;
export const DefaultMultiBuffer = MultiBuffer;
