"""Cellular (WAN) transports: generic WWAN plus 2G/4G/5G generations."""

from .cellular import _LAILA_IDENTIFIABLE_CELLULAR_COMM_PROTOCOL
from .gsm_gprs import _LAILA_IDENTIFIABLE_GSM_COMM_PROTOCOL
from .lte import _LAILA_IDENTIFIABLE_LTE_COMM_PROTOCOL
from .nr5g import _LAILA_IDENTIFIABLE_NR5G_COMM_PROTOCOL

__all__ = [
    "_LAILA_IDENTIFIABLE_CELLULAR_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_GSM_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_LTE_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_NR5G_COMM_PROTOCOL",
]
