"""Wired / bus transports (board + field level).

Working serial-line transports (UART, RS-232, RS-485) on the
point-to-point stream carrier, plus the CAN/CAN-FD transport (ISO-TP
over SocketCAN). Drivers are imported lazily so importing laila never
requires them.
"""

from .can import _LAILA_IDENTIFIABLE_CAN_COMM_PROTOCOL
from .enip import _LAILA_IDENTIFIABLE_ENIP_COMM_PROTOCOL
from .i2c import _LAILA_IDENTIFIABLE_I2C_COMM_PROTOCOL
from .modbus_rtu import _LAILA_IDENTIFIABLE_MODBUS_RTU_COMM_PROTOCOL
from .rs232 import _LAILA_IDENTIFIABLE_RS232_COMM_PROTOCOL
from .rs485 import _LAILA_IDENTIFIABLE_RS485_COMM_PROTOCOL
from .spi import _LAILA_IDENTIFIABLE_SPI_COMM_PROTOCOL
from .uart import _LAILA_IDENTIFIABLE_UART_COMM_PROTOCOL
from .usb import _LAILA_IDENTIFIABLE_USB_COMM_PROTOCOL

__all__ = [
    "_LAILA_IDENTIFIABLE_CAN_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_ENIP_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_I2C_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_MODBUS_RTU_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_RS232_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_RS485_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_SPI_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_UART_COMM_PROTOCOL",
    "_LAILA_IDENTIFIABLE_USB_COMM_PROTOCOL",
]
